[Fortran/gfortran] Disable test to fix failing buildbots (#149)
Several of the AArch64 buildbots are failing due to an undefined reference to
__trampoline_setup when compiling internal_dummy_2.f08. This is probably an
issue with the buildbot configuration, but in the interest of getting them bots
unstuck, the test is being disabled.

Co-authored-by: Tarun Prabhu <tarun.prabhu@gmail.com>