Update google benchmark to v1.9.1 (#222)
* Update google benchmark to v1.9.1

Updated MicroBenchmarks/lib/benchmark/ using update_benchmark.sh with the
change below:

```
diff --git a/MicroBenchmarks/libs/update_benchmark.sh b/MicroBenchmarks/libs/update_benchmark.sh
index b4caa3c9..c1f3e84f 100755
--- a/MicroBenchmarks/libs/update_benchmark.sh
+++ b/MicroBenchmarks/libs/update_benchmark.sh
@@ -9,8 +9,8 @@ echo
 read -p "Press a key to continue, or Ctrl+C to cancel"

 rm -rf benchmark
-git clone https://github.com/google/benchmark.git
-git clone https://github.com/google/googletest.git benchmark/googletest
+git clone --branch=v1.9.1 https://github.com/google/benchmark.git
+git clone --branch=v1.16.0 https://github.com/google/googletest.git benchmark/googletest
 rm -rf benchmark/googletest/.git*
 rm -rf benchmark/.git*
```

* Fix MicroBenchmark build on Linux with clang 18.1.8 (#141)

MicroBenchmarks/libs/benchmark/test/options_test.cc fails to build
on Linux/AArch64 with following error:
error: variable 'actual_iterations' set but not used

This patch adds benchmark::DoNotOptimize(actual_iterations); to
to function BM_explicit_iteration_count in options_test.cc

-Wall and -Werror were being used to compile and I am surprised that
this was not caught by any of the buildbots.
Some versions of clang compile this all fine with -Wall -Werror.

---------

Co-authored-by: Omair Javaid <omair.javaid@linaro.org>