Skip build of unsupported tests with ptrauth_indirect_gotos feature
The following two tests are not compatible with the ptrauth_indirect_gotos
feature supported by mainline LLVM:

1. SingleSource/Regression/C/gcc-c-torture/execute/920501-3.c
2. SingleSource/Regression/C/gcc-c-torture/execute/pr70460.c

Compiling them with that feature enabled would result in the following error:

```
error: addition of address-of-label expressions is not supported with ptrauth indirect gotos
```

This patch disables compiling these tests if ptrauth_indirect_gotos
feature usage is detected.

Co-authored-by: Vladimir Vereschaka <vvereschaka@accesssoftek.com>