[AIX][test-suite] Disable the CoMD benchmark on AIX
This patch disables the CoMD benchmark on AIX. The benchmark fails with the error,
```
CoMD/cmdLineParser.c:13:10: fatal error: 'getopt.h' file not found
#include <getopt.h>
         ^~~~~~~~~~
1 error generated.
```
The getopt.h header actually is not present on AIX. Although getopt is available
under unistd.h, the test actually utilizes getopt_long(). This function is not present
on AIX, hence why this patch disables CoMD.

Differential Revision: https://reviews.llvm.org/D103064