[simd_ops] Update target layout for ARM bitcode files
Since https://github.com/llvm/llvm-project/pull/224012,
we do not overwite the target layout of a module.
This lead to failures on our Arm bots:
fatal error: error in backend: Can't create a MachineFunction using a Module with a
      Target-incompatible DataLayout attached
  Target DataLayout: e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64
  Module DataLayout: e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64

Clang's data layout has an extra "Fi8". Fi refers to the
alignment of function pointers, which is some multiple of 8.

We must have been compiling these bitcode files with clang's
target layout all along, so I think we're safe to update the
layout in the files to match clang's.

They all have the same layout:
$ cat scan.sh
for f in ARM_halide_runtime.bc ARM_tests/*.bc ARM_scalar_tests/*.bc; do
  ~/build-llvm-aarch64/bin/llvm-dis "$f" -o - 2>/dev/null |
    grep -m1 '^target datalayout'
done | sort | uniq -c
$ bash scan.sh
   2779 target datalayout = "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64"

That 2779 is 2x1389 failing tests, plus the halide runtime file
(each test is runtime plus 2 other files).

I disassembled them, changed the layout and re-assembled them:
for f in ARM_halide_runtime.bc ARM_tests/*.bc ARM_scalar_tests/*.bc; do
  tmp=$(mktemp --suffix=.ll)
  ~/build-llvm-aarch64/bin/llvm-dis "$f" -o "$tmp" || exit 1
  sed -i \
    's/e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64/e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64/' \
    "$tmp"
  ~/build-llvm-aarch64/bin/llvm-as "$tmp" -o "$f" || exit 1
  rm "$tmp"
done

After doing this, the tests build and run correctly. The binary size
changes more than I expected, but the disassembled content is the
same for both.

mkdir -p /tmp/simd-before
for f in ARM_halide_runtime.bc ARM_tests/*.bc ARM_scalar_tests/*.bc; do
  out="/tmp/simd-before/${f%.bc}.ll"
  mkdir -p "$(dirname "$out")"
  ~/build-llvm-aarch64/bin/llvm-dis "$f" -o "$out" || exit 1
done

Only target layout lines were added and removed:
$ diff -ru /tmp/simd-before /tmp/simd-after | grep "^-" | grep -v "^--" | sort | uniq
-target datalayout = "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64"
$ diff -ru /tmp/simd-before /tmp/simd-after | grep "^+" | grep -v "^++" | sort | uniq
+target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"