[test-suite] Fix clang build failure due to uniform_real_distribution in SLPVectorization
The newly added file will cause build failure with clang.

test-suite/MicroBenchmarks/SLPVectorization/Versioning.cpp:10:37:
required from ‘void init_data(T*, unsigned int) [with T = int]’
test-suite/MicroBenchmarks/SLPVectorization/Versioning.cpp:28:12:
required from ‘void benchmark_xor_runtime_checks_pass(benchmark::State&)
[with unsigned int N = 4; T = int]’
test-suite/MicroBenchmarks/SLPVectorization/Versioning.cpp:70:1:
required from here
/usr/include/c++/7/bits/random.h:1704:7: error: static assertion failed:
result_type must be a floating point type
       static_assert(std::is_floating_point<_RealType>::value,

Reviewed By: hubert.reinterpretcast

Differential Revision: https://reviews.llvm.org/D107204