[Prolangs-C] Fix "conflicting types" build errors
Correcting these function declarations addresses these compilation
errors:

```
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/loader/sym_tab.c:40:5: error: conflicting types for 'INSERT_IN_SYM_TAB'
   40 | int INSERT_IN_SYM_TAB(char *MODULE,char *LABEL,int LOCATION,enum kind TYPE,
      |     ^
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/loader/sym_tab.h:52:12: note: previous declaration is here
   52 | extern int INSERT_IN_SYM_TAB();
      |            ^
1 error generated.

llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/assembler/sym_tab.c:40:5: error: conflicting types for 'INSERT_IN_SYM_TAB'
   40 | int INSERT_IN_SYM_TAB(char *MODULE,char *LABEL,int LOCATION,enum kind TYPE,
      |     ^
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/assembler/sym_tab.h:52:12: note: previous declaration is here
   52 | extern int INSERT_IN_SYM_TAB();
      |            ^
1 error generated.
```

Since clang 15.x, this has been an error for C programs.